version: '3.8'

services:
  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    extra_hosts:
      - "jdevhomeserver.ddns.net:YOUR_MYSQL_SERVER_IP"
